apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-devops-janitor-event-forwarder-deployment
  namespace: developerautomation-xavgy
  labels:
    project: developerautomation
    department: cloudengineering
    component: azure-devops-janitor
    app: azure-devops-janitor-event-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-devops-janitor-event-forwarder
  template:
    metadata:
      labels:
        project: developerautomation
        department: cloudengineering
        app: azure-devops-janitor-event-forwarder
    spec:
      priorityClassName: selfservice
      containers:
      - name: azure-devops-janitor-event-forwarder
        image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/dfds.developerautomation-xavgy.azure-devops-janitor:azure-devops-janitor-event-forwarder-$(Build.BuildId)
        env:
          - name: AdoClient__ClientAccessToken
            valueFrom:
              secretKeyRef:
                name: ado-credentials
                key: clientAccessToken
          - name: Kafka__Configuration__sasl.username
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: username
          - name: Kafka__Configuration__sasl.password
            valueFrom:
              secretKeyRef:
                name: kafka-credentials
                key: password
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"